// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhRDWibi9aNbbSS_LpAwiz5kV8i1dGd-E',
    appId: '1:40752187330:web:6e023d0edf46609cf2b85b',
    messagingSenderId: '40752187330',
    projectId: 'gallery-440f9',
    authDomain: 'gallery-440f9.firebaseapp.com',
    storageBucket: 'gallery-440f9.firebasestorage.app',
    measurementId: 'G-5Y3XMXE67R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMUv9j3MrL_oBp6NolpabFMhkDNrxQjvU',
    appId: '1:40752187330:android:9f512ec160c948adf2b85b',
    messagingSenderId: '40752187330',
    projectId: 'gallery-440f9',
    storageBucket: 'gallery-440f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDBg6cndOGJQ5mHsiaHhLsWnnZCRGIFcI',
    appId: '1:40752187330:ios:659a73e2da537977f2b85b',
    messagingSenderId: '40752187330',
    projectId: 'gallery-440f9',
    storageBucket: 'gallery-440f9.firebasestorage.app',
    iosBundleId: 'com.example.myGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDBg6cndOGJQ5mHsiaHhLsWnnZCRGIFcI',
    appId: '1:40752187330:ios:659a73e2da537977f2b85b',
    messagingSenderId: '40752187330',
    projectId: 'gallery-440f9',
    storageBucket: 'gallery-440f9.firebasestorage.app',
    iosBundleId: 'com.example.myGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhRDWibi9aNbbSS_LpAwiz5kV8i1dGd-E',
    appId: '1:40752187330:web:c21f524ba61480aef2b85b',
    messagingSenderId: '40752187330',
    projectId: 'gallery-440f9',
    authDomain: 'gallery-440f9.firebaseapp.com',
    storageBucket: 'gallery-440f9.firebasestorage.app',
    measurementId: 'G-Y97VW2JCCS',
  );
}
